language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
os:
  - linux

install:
  - sudo apt-get install qt5-default qt5-qmake
  - curl https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp > testing/catch.hpp

script:
  - qmake qt-todo.pro test=1
  - make
  - ./testing/qt-todo

