name: qt-todo
version: "0.1"
summary: TODO list maker
license: GPL-3.0
description: |
  A simple, memory efficient GUI program for making TODO lists.
  It uses a TSV-style format for storing the lists.
  It allows for adding tasks and marking them as completed, and can work with
  many different lists at once through tabs.

confinement: devmode
base: core18
icon: logo/qt-todo.svg
grade: devel

apps:
  qt-todo:
    command: qt-todo

parts:
  qt-todo:
    source: .
    plugin: qmake
    qt-version: qt5
    project-files: [qt-todo.pro]
    build-packages:
      - binutils
      - qt5-default
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5dbus5